### ISSUE TITLE
Insert replaces all text in Text mode

### ISSUE THREAD

**Issue by JoshMB** [JoshMB/sefaria-wp-plugin#1]
If editing the WordPress post in 'Text' (HTML source) mode, using the plugin replaces the entire post with the returned text.

(This doesn't happen, as far as I can tell, in the 'Visual' (wysiwyg) editor.)

Any ideas, @rneiss?

**Comment by rneiss** [comment]
only use the plugin in visual mode obviously ;)

**Comment by rneiss** [comment]
Line 103 of sefaria-text.php:
https://github.com/JoshMB/sefaria-wp-plugin/blob/master/sefaria-text.php#L103

it should append or something else instead of replace. 

No time now to experiment -- but please feel free too.

**Comment by rneiss** [comment]
fixed: in [759850301](https://github.com/JoshMB/sefaria-wp-plugin/commit/7598503011c67b735136140ee94030a368ad9518)
