### ISSUE TITLE
Insertion point in Visual mode

### ISSUE THREAD

**Issue by JoshMB** [JoshMB/sefaria-wp-plugin#2]
After using the plugin to insert text while editing in 'Visual" (wysiwyg) mode, the insertion point stays within the `<cite>` element. (So that a user has to hit enter a couple times to get back to typing non-cited and non-blockquoted text.)

This isn't a huge issue, but I'm wondering if adding a `&nbsp;` (or something like that) after the `</blockquote>` tag will leave the insertion point where we'd want it to be. (So I'll try that and see if it works.)

**Comment by rneiss** [comment]
fixed here: https://github.com/JoshMB/sefaria-wp-plugin/commit/f6aaed6ed57ac308c9bcbde3c620a82d3a568ef7
